
name: Deploy to Cloud Run (Simple)

on:
  push:
    branches: ["master"]      # Deploy on push to main
  workflow_dispatch:         # Allow manual run

env:
  REGION: ${{ secrets.GCP_REGION }}           # e.g., asia-southeast1
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}   # your GCP project ID
  REPO: ${{ secrets.AR_REPO }}                # Artifact Registry repo name
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}   # Cloud Run service name
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.AR_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate using service account JSON
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud SDK
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify gcloud auth
        run: gcloud auth list

      # Configure Docker to push to Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      # Build & push Docker image
      - name: Build image
        run: docker build -t "$IMAGE" .
      - name: Push image
        run: docker push "$IMAGE"

      # Deploy to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --timeout 10m \
            --add-cloudsql-instances "${{ secrets.GCP_CLOUDSQL_INSTANCE_NAME }}" \
            --set-env-vars "DB_HOST=/cloudsql/${{ secrets.GCP_CLOUDSQL_INSTANCE_NAME }},DB_PORT=3306,DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_NAME=${{ secrets.DB_NAME }},DB_AUTO_SYNCHRONIZE=true"

      # Optional: print the URL
      - name: Show Service URL
        run: |
          gcloud run services describe "$SERVICE" --region "$REGION" \
            --format='value(status.url)'
